// AUTO-GENERATED by scripts/build-changelog.ts.
// Source of truth is the project's git log. Do not edit by hand — your changes will
// be overwritten on the next build. To change what appears here, change the commit
// history (e.g. write better commit messages: feat(scope): user-visible description).

export type ChangelogType = 'feat' | 'fix' | 'perf' | 'revert';

export interface ChangelogEntry {
  hash: string;
  date: string;
  type: ChangelogType;
  scope: string | null;
  title: string;
}

export const CHANGELOG: readonly ChangelogEntry[] = [
  {
    "hash": "67db3bc",
    "date": "2026-05-10",
    "type": "fix",
    "scope": "ui",
    "title": "Prose heading color + drop Changelog from header + footer columns"
  },
  {
    "hash": "b96c3a0",
    "date": "2026-05-09",
    "type": "feat",
    "scope": null,
    "title": "Editorial redesign + compare mode + saved scenarios + privacy receipts"
  },
  {
    "hash": "09eddad",
    "date": "2026-05-09",
    "type": "fix",
    "scope": "domain",
    "title": "Remove next.config www→apex redirect to break Vercel loop"
  },
  {
    "hash": "dfa6017",
    "date": "2026-05-09",
    "type": "feat",
    "scope": null,
    "title": "Rebrand to tokenmath.dev + monetization pivot + pricing auto-refresh"
  },
  {
    "hash": "46ab3e3",
    "date": "2026-05-09",
    "type": "fix",
    "scope": "theme",
    "title": "Dark is the brand default — ignore system prefers-color-scheme"
  },
  {
    "hash": "6b70381",
    "date": "2026-05-09",
    "type": "fix",
    "scope": "ui",
    "title": "Tighten calculator controls row"
  },
  {
    "hash": "a302113",
    "date": "2026-05-09",
    "type": "fix",
    "scope": "ux",
    "title": "UX forensic audit — 18 findings across calculator, a11y, copy"
  },
  {
    "hash": "1baac59",
    "date": "2026-05-09",
    "type": "fix",
    "scope": "pricing-data",
    "title": "Keep Verified date on one line (whitespace-nowrap)"
  },
  {
    "hash": "8c1dfce",
    "date": "2026-05-09",
    "type": "feat",
    "scope": null,
    "title": "Round 2 — drop GitHub/socials, add OpenAI, accurate Vertex copy"
  },
  {
    "hash": "aaebf0a",
    "date": "2026-05-09",
    "type": "feat",
    "scope": "content",
    "title": "About, privacy, pricing-data pages"
  },
  {
    "hash": "2ad87a0",
    "date": "2026-05-09",
    "type": "feat",
    "scope": "security",
    "title": "CSP + security headers in next.config.ts"
  },
  {
    "hash": "e5f3b93",
    "date": "2026-05-09",
    "type": "feat",
    "scope": "analytics",
    "title": "Microsoft Clarity with prompt + cost masking"
  },
  {
    "hash": "2eb5d4f",
    "date": "2026-05-09",
    "type": "feat",
    "scope": "analytics",
    "title": "Vercel Analytics + Speed Insights, custom events"
  },
  {
    "hash": "32bc055",
    "date": "2026-05-09",
    "type": "feat",
    "scope": null,
    "title": "Public/ads.txt + app-ads.txt placeholders"
  },
  {
    "hash": "99d77d3",
    "date": "2026-05-09",
    "type": "feat",
    "scope": "ads",
    "title": "Provider switch (none/adsense/mediavine) + AdSlot component"
  },
  {
    "hash": "346133e",
    "date": "2026-05-09",
    "type": "feat",
    "scope": "seo",
    "title": "Per-page Breadcrumb + FAQPage + SoftwareApplication JSON-LD"
  },
  {
    "hash": "96238f0",
    "date": "2026-05-09",
    "type": "feat",
    "scope": "content",
    "title": "MDX pipeline + 5 model pages under /token-calculator/[model]"
  },
  {
    "hash": "f0f35f7",
    "date": "2026-05-09",
    "type": "feat",
    "scope": "seo",
    "title": "Public/llms.txt static + scripts/build-llms-full.ts wired to prebuild"
  },
  {
    "hash": "318e8dd",
    "date": "2026-05-09",
    "type": "feat",
    "scope": "seo",
    "title": "App/sitemap.ts, app/robots.ts, manifest.ts, custom favicon set"
  },
  {
    "hash": "a86b2c0",
    "date": "2026-05-09",
    "type": "feat",
    "scope": "seo",
    "title": "Metadata, OG default, JSON-LD helpers (WebApp + Organization)"
  },
  {
    "hash": "8f8642b",
    "date": "2026-05-09",
    "type": "feat",
    "scope": "ui",
    "title": "Calculator + ModelPicker + ResultCard wired to tokenizer"
  },
  {
    "hash": "cc6af8b",
    "date": "2026-05-09",
    "type": "feat",
    "scope": "lib",
    "title": "Tokenizers/{claude,gemini} + index countTokens API + Web Worker for >50k chars"
  },
  {
    "hash": "4c7b2a0",
    "date": "2026-05-09",
    "type": "feat",
    "scope": "lib",
    "title": "Pricing.ts with MODELS[] + dataAsOf timestamps"
  },
  {
    "hash": "31de982",
    "date": "2026-05-09",
    "type": "feat",
    "scope": "ui",
    "title": "Footer with Vertex Network blind link + sister-site modal"
  },
  {
    "hash": "c147a6b",
    "date": "2026-05-09",
    "type": "feat",
    "scope": "ui",
    "title": "Header with desktop nav + mobile hamburger drawer (a11y, focus trap)"
  },
  {
    "hash": "1b71a57",
    "date": "2026-05-09",
    "type": "feat",
    "scope": "ui",
    "title": "Theme tokens, fonts (Inter + Geist Mono), root layout, dark default"
  }
] as const;

export const CHANGELOG_GENERATED_AT = '2026-05-10T07:27:05.264Z';
