// AUTO-GENERATED by scripts/build-changelog.ts.
// Source of truth is the project's git log. Do not edit by hand — your changes will
// be overwritten on the next build. To change what appears here, change the commit
// history (write better commit subjects: feat(scope): user-visible description).
//
// Per spec §7 the shape is locked to { date, title } only.

export interface ChangelogEntry {
  date: string;
  title: string;
}

export const CHANGELOG: readonly ChangelogEntry[] = [
  {
    "date": "2026-05-10",
    "title": "Auto-generate from git log + render titles only"
  },
  {
    "date": "2026-05-10",
    "title": "Prose heading color + drop Changelog from header + footer columns"
  },
  {
    "date": "2026-05-09",
    "title": "Editorial redesign + compare mode + saved scenarios + privacy receipts"
  },
  {
    "date": "2026-05-09",
    "title": "Remove next.config www→apex redirect to break Vercel loop"
  },
  {
    "date": "2026-05-09",
    "title": "Rebrand to tokenmath.dev + monetization pivot + pricing auto-refresh"
  },
  {
    "date": "2026-05-09",
    "title": "Dark is the brand default — ignore system prefers-color-scheme"
  },
  {
    "date": "2026-05-09",
    "title": "Tighten calculator controls row"
  },
  {
    "date": "2026-05-09",
    "title": "UX forensic audit — 18 findings across calculator, a11y, copy"
  },
  {
    "date": "2026-05-09",
    "title": "Keep Verified date on one line (whitespace-nowrap)"
  },
  {
    "date": "2026-05-09",
    "title": "Round 2 — drop GitHub/socials, add OpenAI, accurate Vertex copy"
  },
  {
    "date": "2026-05-09",
    "title": "About, privacy, pricing-data pages"
  },
  {
    "date": "2026-05-09",
    "title": "CSP + security headers in next.config.ts"
  },
  {
    "date": "2026-05-09",
    "title": "Microsoft Clarity with prompt + cost masking"
  },
  {
    "date": "2026-05-09",
    "title": "Vercel Analytics + Speed Insights, custom events"
  },
  {
    "date": "2026-05-09",
    "title": "Public/ads.txt + app-ads.txt placeholders"
  },
  {
    "date": "2026-05-09",
    "title": "Provider switch (none/adsense/mediavine) + AdSlot component"
  },
  {
    "date": "2026-05-09",
    "title": "Per-page Breadcrumb + FAQPage + SoftwareApplication JSON-LD"
  },
  {
    "date": "2026-05-09",
    "title": "MDX pipeline + 5 model pages under /token-calculator/[model]"
  },
  {
    "date": "2026-05-09",
    "title": "Public/llms.txt static + scripts/build-llms-full.ts wired to prebuild"
  },
  {
    "date": "2026-05-09",
    "title": "App/sitemap.ts, app/robots.ts, manifest.ts, custom favicon set"
  },
  {
    "date": "2026-05-09",
    "title": "Metadata, OG default, JSON-LD helpers (WebApp + Organization)"
  },
  {
    "date": "2026-05-09",
    "title": "Calculator + ModelPicker + ResultCard wired to tokenizer"
  },
  {
    "date": "2026-05-09",
    "title": "Tokenizers/{claude,gemini} + index countTokens API + Web Worker for >50k chars"
  },
  {
    "date": "2026-05-09",
    "title": "Pricing.ts with MODELS[] + dataAsOf timestamps"
  },
  {
    "date": "2026-05-09",
    "title": "Footer with Vertex Network blind link + sister-site modal"
  },
  {
    "date": "2026-05-09",
    "title": "Header with desktop nav + mobile hamburger drawer (a11y, focus trap)"
  },
  {
    "date": "2026-05-09",
    "title": "Theme tokens, fonts (Inter + Geist Mono), root layout, dark default"
  }
] as const;

export const CHANGELOG_GENERATED_AT = '2026-05-10T08:30:01.991Z';
