/**
 * Generates lib/changelog.generated.ts from `git log`.
 *
 * Per spec §7 the changelog data shape is locked to { date, title } only — no scope, no
 * type, no hash, no body. This is a deliberate privacy + spec-compliance choice: the page
 * shows what shipped and when, nothing more. Long-form release notes belong elsewhere
 * (we deliberately don't link out to GitHub Releases either).
 *
 * Wired to `prebuild` in package.json so the file is fresh on every build (local + CI).
 *
 * Falls back to an empty CHANGELOG array if git is unavailable or the working tree has
 * no matching commits — the page renders an "empty state" without failing the build.
 */

import { execSync } from "node:child_process";
import { writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(here, "..");
const OUT = resolve(ROOT, "lib/changelog.generated.ts");

// Conventional-commit types that show up in a user-visible changelog. We deliberately
// skip chore/refactor/test/docs/ci/style/build — those are internal noise.
const INCLUDE_TYPES = ["feat", "fix", "perf", "revert"] as const;
type IncludeType = (typeof INCLUDE_TYPES)[number];

const COMMIT_PATTERN = /^(feat|fix|perf|revert)(?:\([^)]+\))?:\s*(.+)$/;

interface GeneratedEntry {
  date: string;
  title: string;
}

function readGitLog(): GeneratedEntry[] {
  let raw = "";
  try {
    raw = execSync("git log --no-merges --pretty=format:%aI%x09%s", {
      cwd: ROOT,
      encoding: "utf8",
      stdio: ["ignore", "pipe", "ignore"],
    });
  } catch {
    return [];
  }

  const entries: GeneratedEntry[] = [];
  for (const line of raw.split("\n")) {
    const tab = line.indexOf("\t");
    if (tab === -1) continue;
    const iso = line.slice(0, tab);
    const subject = line.slice(tab + 1);
    if (!iso || !subject) continue;
    const match = subject.match(COMMIT_PATTERN);
    if (!match) continue;
    const [, rawType, rawTitle] = match;
    if (!INCLUDE_TYPES.includes(rawType as IncludeType)) continue;
    entries.push({
      date: iso.slice(0, 10),
      title: capitalize(rawTitle.trim()),
    });
  }
  return entries;
}

function capitalize(s: string): string {
  if (s.length === 0) return s;
  return s.charAt(0).toUpperCase() + s.slice(1);
}

function render(entries: GeneratedEntry[]): string {
  const header = `// AUTO-GENERATED by scripts/build-changelog.ts.
// Source of truth is the project's git log. Do not edit by hand — your changes will
// be overwritten on the next build. To change what appears here, change the commit
// history (write better commit subjects: feat(scope): user-visible description).
//
// Per spec §7 the shape is locked to { date, title } only.
`;
  return `${header}
export interface ChangelogEntry {
  date: string;
  title: string;
}

export const CHANGELOG: readonly ChangelogEntry[] = ${JSON.stringify(entries, null, 2)} as const;

export const CHANGELOG_GENERATED_AT = '${new Date().toISOString()}';
`;
}

async function main(): Promise<void> {
  const entries = readGitLog();
  await writeFile(OUT, render(entries), "utf8");
  console.log(`✓ wrote ${OUT} (${entries.length} ${entries.length === 1 ? "entry" : "entries"})`);
}

main().catch((err: unknown) => {
  console.error(err);
  process.exit(1);
});
