/**
 * Generates lib/changelog.generated.ts from `git log`.
 *
 * The site's changelog is a derivative of the project's commit history — every feat /
 * fix / perf / revert that lands on main becomes one entry, no manual maintenance.
 * Wired to `prebuild` in package.json so the file is fresh on every build (local + CI).
 *
 * Falls back to an empty CHANGELOG array if git is unavailable or the working tree has
 * no matching commits — the page renders an "empty state" without failing the build.
 */

import { execSync } from 'node:child_process';
import { writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(here, '..');
const OUT = resolve(ROOT, 'lib/changelog.generated.ts');

// Conventional-commit types that show up in a user-visible changelog. We deliberately
// skip chore/refactor/test/docs/ci/style/build — those are internal noise.
const INCLUDE_TYPES = ['feat', 'fix', 'perf', 'revert'] as const;
type IncludeType = (typeof INCLUDE_TYPES)[number];

const COMMIT_PATTERN = /^(feat|fix|perf|revert)(?:\(([^)]+)\))?:\s*(.+)$/;

interface GeneratedEntry {
  hash: string;
  date: string;
  type: IncludeType;
  scope: string | null;
  title: string;
}

function readGitLog(): GeneratedEntry[] {
  let raw = '';
  try {
    raw = execSync('git log --no-merges --pretty=format:%h%x09%aI%x09%s', {
      cwd: ROOT,
      encoding: 'utf8',
      stdio: ['ignore', 'pipe', 'ignore'],
    });
  } catch {
    return [];
  }

  const entries: GeneratedEntry[] = [];
  for (const line of raw.split('\n')) {
    const [hash, iso, subject] = line.split('\t');
    if (!hash || !iso || !subject) continue;
    const match = subject.match(COMMIT_PATTERN);
    if (!match) continue;
    const [, rawType, rawScope, rawTitle] = match;
    if (!INCLUDE_TYPES.includes(rawType as IncludeType)) continue;
    entries.push({
      hash,
      date: iso.slice(0, 10),
      type: rawType as IncludeType,
      scope: rawScope ?? null,
      title: capitalize(rawTitle.trim()),
    });
  }
  return entries;
}

function capitalize(s: string): string {
  if (s.length === 0) return s;
  return s.charAt(0).toUpperCase() + s.slice(1);
}

function render(entries: GeneratedEntry[]): string {
  const header = `// AUTO-GENERATED by scripts/build-changelog.ts.
// Source of truth is the project's git log. Do not edit by hand — your changes will
// be overwritten on the next build. To change what appears here, change the commit
// history (e.g. write better commit messages: feat(scope): user-visible description).
`;
  return `${header}
export type ChangelogType = ${INCLUDE_TYPES.map((t) => `'${t}'`).join(' | ')};

export interface ChangelogEntry {
  hash: string;
  date: string;
  type: ChangelogType;
  scope: string | null;
  title: string;
}

export const CHANGELOG: readonly ChangelogEntry[] = ${JSON.stringify(entries, null, 2)} as const;

export const CHANGELOG_GENERATED_AT = '${new Date().toISOString()}';
`;
}

async function main(): Promise<void> {
  const entries = readGitLog();
  await writeFile(OUT, render(entries), 'utf8');
  console.log(`✓ wrote ${OUT} (${entries.length} ${entries.length === 1 ? 'entry' : 'entries'})`);
}

main().catch((err: unknown) => {
  console.error(err);
  process.exit(1);
});
